; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
	platform = espressif32
	framework = arduino
	monitor_speed = 115200
	upload_speed  = 460800
[esp32s3]
    ;board_build.partitions = boards/partitio_4MB.csv    ;  4MB Flash
    ;board_build.partitions = boards/partitio_8MB.csv    ;  8MB Flash
    board_build.partitions = boards/partition_16MB.csv   ; 16MB Flash

    ;board = ESP32-S3-DevKitC-1-N8R2  ;  8 MB Flash, 2MB quad PSRAM  *1)
    ;board = ESP32-S3-DevKitC-1-N8R8  ;  8 MB Flash, 8MB octo PSRAM  *2)
    board = ESP32-S3-DevKitC-1-N16R8 ; 16 MB Flash, 8MB octo PSRAM  *2)

[env:esp32s3]
    board = ${esp32s3.board}
    board_build.partitions = ${esp32s3.board_build.partitions}
	lib_deps = 
		bblanchon/ArduinoJson@^7.2.0
		;https://github.com/schreibfaul1/ESP32-audioI2S
		https://github.com/esphome/ESP32-audioI2S.git
		https://github.com/tueddy/PN5180-Library.git#f776e66
